apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - repos.yaml
  - grafana-loki-bloom.yaml
  - kube-prometheus-stack.yaml
  - grafana-tempo.yaml
  - opentelemetry.yaml
