---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-repo
  namespace: monitoring
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://grafana.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community-repo
  namespace: monitoring
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: v1
kind: Secret
metadata:
  name: open-telemetry-repo
  namespace: monitoring
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
